---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.labels.app }}
spec:
  selector:             
    app: {{ .Values.labels.app }}
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}