---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    k8s-app: cadvisor
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    k8s-app: cadvisor